spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieclub
    username: root
    password: admin
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:D:\Z_WOJCIECH\KURSY\JAVA\JAVA-START\3.Spring\1.Spring-kurs\38. Movieclub - projekt\movieclub\uploads
app:
  storage:
    location: D:\Z_WOJCIECH\KURSY\JAVA\JAVA-START\3.Spring\1.Spring-kurs\38. Movieclub - projekt\movieclub\uploads